theme: jekyll-theme-minimal
logo: https://bioboot.github.io/bimm143_F25/assets/img/logo.png
title: Portfolio

## Index of Material

* Introductory Classes

* R Fundementals

Class 04 [R fundementals](class04/class04.pdf)

Class 05 [Data viz with ggplot](class05/class05.pdf)

* Genomics

* Structural
